version: '3'

services:

   chatbot:
       container_name: chatbot
       image: virtualwife/chatbot:latest
       ports:
        - 8000:8000
       environment:
         - TZ=${TIMEZONE}
       env_file:
         - "${ENV_FILE:-.env}"
       networks:
         - virtualwife
   chatvrm:
      container_name: chatvrm
      image: virtualwife/chatvrm:latest
      environment:
        - TZ=${TIMEZONE}  
      env_file:
        - "${ENV_FILE:-.env}"
      networks:
        - virtualwife
   gateway:
     container_name: gateway
     image: virtualwife/gateway:latest
     restart: always
     ports:
       - ${NGINX_HTTP_PORT:-80}:80
       - ${NGINX_HTTPS_PORT:-443}:443
     environment:
       - TZ=${TIMEZONE}
     env_file:
       - "${ENV_FILE:-.env}"
     networks:
       - virtualwife

networks:
  virtualwife:
    driver: bridge
